# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Kavel.Kavel
PackageVersion: 0.2.0
InstallerType: portable
Commands:
- kavel
ReleaseDate: 2026-09-14
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hanshs474/kavel-go/releases/download/v0.2.0/kavel-windows-amd64.exe
  InstallerSha256: 4E9080AE942FED0F70AF1B478A7E6EE53D0F3717AE84D8D93875F081ABD1788D
- Architecture: arm64
  InstallerUrl: https://github.com/hanshs474/kavel-go/releases/download/v0.2.0/kavel-windows-arm64.exe
  InstallerSha256: 7961A39CFD9E5ADD7AA3577AD7C9C5D2650F0CBC6EB63BEBE007A8E478FFCE32
ManifestType: installer
ManifestVersion: 1.12.0
